server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  requestLog:
    appenders:
      - type: console
threads: 20
repository:
  host: parisiancocktail.socrate.vsct.fr
  port: 53000
nsqLookup:
  host: parisiancocktail.socrate.vsct.fr
  port: 54171
nsqProducer:
  host: parisiancocktail.socrate.vsct.fr
  tcpPort: 55556
  httpPort: 55555
periodicScheduler:
  current:
    periodMilli: 11000
  pending:
    periodMilli: 7000
logging:
    level: INFO
    loggers:
      com.vsct.dt: INFO
    appenders:
      - type: console
commitTimeout: 10
handledHaproxyRefreshPeriodSecond: 20